### ISSUE TITLE
ajouter medaille de bronze

### ISSUE THREAD

**Issue by hels237** [hels237/mon_site_web#2]
ajouter la medaille e bronze dans notre site dans la partie recompense

**Comment by o-pirata** [comment]
![casal](https://github.com/hels237/mon_site_web/assets/38570493/3e02855b-7954-440a-b0bf-e26855d83070)

**Comment by o-pirata** [comment]
I not speac english i am from Brasil, and canto intend,ALL english, but Ivan read read that vas is tecnical, OK!
